name: Tests

on:
  push:
    branches: [ main, feat/gcp-deployment ]
  pull_request:
    branches: [ main, feat/gcp-deployment ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm ci
        npm install -D vitest@0.33.0 @vitest/coverage-v8@0.33.0 @testing-library/dom @testing-library/jest-dom @testing-library/react @testing-library/user-event drizzle-orm@0.42.0 istanbul-lib-source-maps@4.0.1 @replit/vite-plugin-shadcn-theme-json --legacy-peer-deps

    - name: Create theme.json
      run: |
        mkdir -p client
        cp theme.json client/theme.json

    - name: Run tests
      run: npm test
      env:
        CI: true
        NODE_ENV: test
        VITEST_COVERAGE_PROVIDER: v8
        SKIP_OPENAI_TEST: true
        OPENAI_API_KEY: "test-key"

    - name: Run coverage
      run: npm run test:coverage
      env:
        CI: true
        NODE_ENV: test
        VITEST_COVERAGE_PROVIDER: v8
        SKIP_OPENAI_TEST: true
        OPENAI_API_KEY: "test-key" 